#ifndef OPENSSL_STUB_H
#define OPENSSL_STUB_H

#define OPENSSL_NO_DEPRECATED 1
#define OPENSSL_NO_DYNAMIC_ENGINE 1
#define OPENSSL_NO_STATIC_ENGINE 1
#define OPENSSL_NO_ENGINE 1
#define OPENSSL_NO_DEVCRYPTOENG 1
#define OPENSSL_NO_ASYNC 1
#define OPENSSL_NO_CRYPTO_MDEBUG 1
#define OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE 1
#define OPENSSL_NO_EC_NISTP_64_GCC_128 1
#define OPENSSL_NO_EGD 1
#define OPENSSL_NO_EXTERNAL_TESTS 1
#define OPENSSL_NO_FUZZ_AFL 1
#define OPENSSL_NO_FUZZ_LIBFUZZER 1
#define OPENSSL_NO_HEARTBEATS 1
#define OPENSSL_NO_MSAN 1
#define OPENSSL_NO_SCTP 1
#define OPENSSL_NO_SSL_TRACE 1
#define OPENSSL_NO_SSL3 1
#define OPENSSL_NO_SSL3_METHOD 1
#define OPENSSL_NO_UBSAN 1
#define OPENSSL_NO_UNIT_TEST 1
#define OPENSSL_NO_WEAK_SSL_CIPHERS 1
#define OPENSSL_NO_DYNAMIC_ENGINE 1

#define EVP_H_MISSING 1
#define PROVIDER_H_MISSING 1

#endif /* OPENSSL_STUB_H */ 